### ISSUE TITLE
Uninstalling Mod Causes Crashes when Opening the Map.

### ISSUE THREAD

**Issue by SolHaku** [rolopogo/ValheimMods#5] opened 2021-02-26 05:41 UTC
Mod removed icons, disabled placement of icons.

After uninstalling it, reran fresh vanilla, game crashes when I open the map in that world (I assume due to null map file, or incorrect map file)

The only way to avoid crashes is to reinstall the mod and have no map icons, or the map is corrupted permanently.

**Comment by rolopogo** [comment] 2021-02-26 10:20
Duplicate of #4 
Resolved in 1.1.0

**Closed by rolopogo** 2021-02-26 10:20 UTC
