### ISSUE TITLE
Broken Map

### ISSUE THREAD

**Issue by Xynon7** [rolopogo/ValheimMods#3] opened 2021-02-26 03:09 UTC
When I and my friend installed this mod, our maps no longer had any pins, beds, elders, anything but the basic map texture.

**Comment by nitefang** [comment] 2021-02-26 03:31
Same thing happened to me, also could no longer add pins. Uninstalled which also lead to issue #4

**Comment by hugsb4drugs** [comment] 2021-02-26 04:59
Same thing happened to me after i had died for the first time with this mod. 
Cannot add new pins or see any, cannot see any other players, and coordinates are no longer shown on map or minimap.
Shared map exploration still works however

**Comment by rolopogo** [comment] 2021-02-26 10:20
Duplicate of #4 
Resolved in 1.1.0

**Closed by rolopogo** 2021-02-26 10:20 UTC

**Comment by nitefang** [comment] 2021-02-26 18:10
Issue totally resolved! Thanks again!
