### ISSUE TITLE
Uninstalling causes large FPS drops in logout location

### ISSUE THREAD

**Issue by Xynon7** [rolopogo/ValheimMods#4] opened 2021-02-26 03:11 UTC
After issue #3 broke our maps, my friend and I uninstalled this mod. However, the location we logged out in has unplayable levels of FPS drop, to the point where only the server admin can actually load in, and even they have ~3 fps there

**Comment by nitefang** [comment] 2021-02-26 03:30
Exact same situation here.

**Comment by nitefang** [comment] 2021-02-26 03:55
I am doing some testing with this. Reinstalling the mod fixes the FPS issue.

With the mod installed, disabling everything in the config file also causes the FPS issue. 

The map save file is affected, if another player loads the same map they have the same issue. 

The console commands "resetmap" and "exploremap" have no effect.

**Comment by nitefang** [comment] 2021-02-26 04:00
Running the mod with everything disabled in the config except for the options under "[Pins]" enabled has no FPS drop issues.

So if anything related to the pins/deathmarkers is disabled or uninstalled, the mod breaks the game.

**Comment by o0Karvanaama0o** [comment] 2021-02-26 04:19
Having the same exact issue, and the culprit we narrowed down to dying, after which nothing shows up on the map and the map became unplayaple after uninstall. Hoping for a fix, felt like a really solid system.

**Comment by nitefang** [comment] 2021-02-26 04:20
It is related to the persistent death markers. If you are far enough away from them the game runs fine. If you open the map and you are zoomed in enough that you can't see one it runs fine. If you click and drag the map and reveal a death marker, it becomes insanely unstable, a frame lasts 20-30 seconds.

**Comment by o0Karvanaama0o** [comment] 2021-02-26 04:29
We lost all markers, even the death markers and after uninstalling everything went sideways, fortunately the map was fresh so no real damage done, but yeah, feels like a really solid system, would really love to see it working right someday ;)

**Comment by nitefang** [comment] 2021-02-26 04:50
I'm not sure if you noticed or not, maybe it wasn't the same for you. When I uninstalled all the markers came back, including I think previously removed death markers. I tried installing mods to remove the death markers but nothing worked.

**Comment by Kinscor** [comment] 2021-02-26 05:36
Just throwing in our groups info that we've gathered on this as well. This seems to break the characters map on whichever server you join with it enabled, once you log out it breaks your map to the point that it lags out your game even in the vanilla version when joining with the same character. However, using a fresh character after uninstalling works perfectly fine as well as using the corrupted character on a fresh world/server. So luckily it seems that the mod damage is limited to the servers you used it on. Then again, had you of spent hours in that server......not so good cause until this is patched, that server will be unplayable with the character you used.

**Comment by NordikaMan** [comment] 2021-02-26 05:51
Uninstalling this mod made my world unplayable. 180hrs on that world so I'd like to not lose it...

**Comment by nitefang** [comment] 2021-02-26 06:03
@Kinscor 

That is very useful info though. It is easier to recreate a character than it is to recreate a map. Thank you for the info!

**Comment by Kinscor** [comment] 2021-02-26 07:00
Also another update, our work around currently is to make a new character.
STEPS: Install the mod again so the game runs, put all your items in a chest and screenshot your skills. Close out the game and uninstall the mod. Reboot the game and using a fresh character on a solo world you can use the in-game cheats to give all your levels back and then rejoin the borked server and grab your items. However, we still haven't found a way to restore map data so that's still a loss. Recipes can be reclaimed just by picking up stored items. We still have our corrupted characters on standby in case a patch fixes the problem but you can delete the old character if you want to. We got lucky and have someone who didn't use the mod so we are restoring our map markers off of that but yeah. Hopefully this does get patched.

**Comment by rolopogo** [comment] 2021-02-26 10:19
This was caused by trying to send a null ping in Minimap's update, causing the death pin spam. I've implemented a fix for the death spin spam, and when loading a map it should now filter pins that overlap. I hope this fixes all of your maps and markers!
Resolved in 1.1.0

**Closed by rolopogo** 2021-02-26 10:19 UTC

**Comment by nitefang** [comment] 2021-02-26 18:09
Thank you sooooo much for fixing this! Everything appears to work fine now! I'm happily using this mod instead of MapShareSync thanks to the additional features you've included. I gave it a thumbsup on thunderbolt and will endorse it on Nexus if you add it there!
